<a href="https://colab.research.google.com/github/dgpay/alpha/blob/master/AlphaOtherWayBeforecrash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
install.packages("igraph")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [9]:
library(igraph)

files <- list.files(path="/content/", pattern="*.edges", full.names=TRUE, recursive=FALSE)
lapply(files, function(x) {
    t <- read.table(x, header=TRUE) # load file
    # apply function
    out <- function(t)
    # write to file
    write.table(out, "path/to/output", sep="\t", quote=FALSE, row.names=FALSE, col.names=TRUE)

    
    # print(tab)
    links <- data.frame(
        source=c(t[1]),
        target=c(t[2])
        )

    # create the network object
    network <- graph_from_data_frame(d=links, directed=T) 
    # print_all(network)
    arr<-alpha.centrality(network,alpha = 0.7)
    a<-max(arr) #nilai alpha terbesar
    indx<-match(c(a),arr) #cari index ke berapa
    IdNode=V(network) #ini idNode nya dari setiap buletan ego
    print(a)
    print(indx)
    print(IdNode)
    V(network)[indx] #ini vertex yang kuatnya


})


# ===========inputan batas=========================================
tab<-read.table ("/content/12831.edges" , header = TRUE)
# print(tab)
links <- data.frame(
    source=c(tab[1]),
    target=c(tab[2])
    )

# create the network object
network <- graph_from_data_frame(d=links, directed=T) 
# print_all(network)
plot(network)
arr<-alpha.centrality(network,alpha = 0.5)
a<-max(arr) #nilai alpha terbesar
indx<-match(c(a),arr) #cari index ke berapa
IdNode=V(network) #ini idNode nya dari setiap buletan ego

print(indx)
print(IdNode)
V(network)[indx] #ini vertex yang kuatnya

#==============================Nanti======================================

sprintf("lalala %i",IdNode[indx])



tab<-read.table ("/content/12831.circles" , header = FALSE)
circle_name <-tab[1,2]
tab1<-read.table ("/content/12831.feat" , header = FALSE)
net<- as.matrix(tab)
tab2<-read.table ("/content/12831.featnames" , header = FALSE)
net1<- as.matrix(tab2)
# print(net[1,])
# print(net[,1])
IdxFeat<-match(1260231,net)
# for (i in net){
#   if (net[IdxFeat,i] == 1) {
#     print(net1[i,1])
#   }
# }



[1] 135.0056
[1] 215
+ 220/220 vertices, named, from d90f560:
  [1] 17116707  380580781 221036078 107830991 151338729 19705747  222261763
  [8] 19933035  158419434 149538028 364971269 100581193 113058991 406628822
 [15] 460282402 280935165 285312927 279787626 394263193 254839786 204317520
 [22] 67864340  270449528 153226312 124528830 220368467 206923844 207594668
 [29] 451250774 6581292   34428380  196327549 274153775 324201646 88097807 
 [36] 276308596 16870853  314316607 299715516 276577539 107511013 258140947
 [43] 123371682 461410856 117901353 56860418  43003845  413275344 358775055
 [50] 307458983 69592091  35148062  57490887  37699718  148519842 225444667
 [57] 283306479 220068522 155661154 400689940 72818790  195475105 157829215
 [64] 134940306 31414569  131613362 115221382 200559228 439788025 262340283
+ ... omitted several vertices
[1] 3.62014
[1] 77
+ 95/95 vertices, named, from 54b014b:
 [1] 16216637  30690708  17859804  15465769  195409031 4126501   18109441 
 [8] 25615305 

[[1]]
+ 1/? vertex, named, from d90f560 (deleted):
[1] 14925700

[[2]]
+ 1/? vertex, named, from 54b014b (deleted):
[1] 23484510

[[3]]
+ 1/? vertex, named, from c47f646 (deleted):
[1] 6945012

[[4]]
+ 1/? vertex, named, from c0fb52d (deleted):
[1] 77888423

[[5]]
+ 1/? vertex, named, from c2e109b (deleted):
[1] 42343110

[[6]]
+ 1/? vertex, named, from f69b1dd (deleted):
[1] 22959778

[[7]]
+ 1/? vertex, named, from 90dec77 (deleted):
[1] 17938475

[[8]]
+ 1/? vertex, named, from 5291ce1 (deleted):
[1] 14790748

[[9]]
+ 1/? vertex, named, from cb78a6f (deleted):
[1] 104989762

[[10]]
+ 1/? vertex, named, from c15a132 (deleted):
[1] 52066462

[[11]]
+ 1/? vertex, named, from ec98276 (deleted):
[1] 783214

[[12]]
+ 1/? vertex, named, from 23d9bad (deleted):
[1] 80945435

[[13]]
+ 1/? vertex, named, from d4e02b7 (deleted):
[1] 11752272

[[14]]
+ 1/? vertex, named, from af28361 (deleted):
[1] 19785044

[[15]]
+ 1/? vertex, named, from 9750fd6 (deleted):
[1] 23852686

[[16]]
+ 1/? vertex, 

[1] 212
+ 236/236 vertices, named, from df27518:
  [1] 18498878  14305022  22253     15540222  7415132   17129553  15911247 
  [8] 14087951  57378470  19479427  29294520  13652832  174958347 1765921  
 [15] 14710479  20496869  663463    3191321   1186      13141442  883301   
 [22] 1371101   1678471   8479062   9283582   728163    12800212  19094625 
 [29] 14        15236339  13462502  14178728  14163141  17729005  377821426
 [36] 15639334  713263    586       5994452   13019862  15459980  47       
 [43] 380       6088382   15583257  16353769  136865608 10013512  8630562  
 [50] 62415556  14819149  20904050  528       25583917  35357461  6735     
 [57] 652193    10476462  2727051   40198602  1566521   255617445 2372     
 [64] 551433993 17561826  17384098  18974638  6001592   6331462   15384741 
+ ... omitted several vertices


+ 1/236 vertex, named, from df27518:
[1] 1260231

[1] "lalala 212"

In [10]:
set.seed(1234)
# initialize array, giving dimensions
myArray <- array(0, dim=c(2,2,3))

for(i in 1:3){
  rnormRdn <- matrix(rnorm(n = 4), nrow = 2, ncol = 2)
  print("New random matrix that should be appended is:")
  print(rnormRdn)
  myArray[,,i] <- rnormRdn
  print("New random matrix not correctly apended on after first iteration:")
  print(myArray)
}

[1] "New random matrix that should be appended is:"
           [,1]      [,2]
[1,] -1.2070657  1.084441
[2,]  0.2774292 -2.345698
[1] "New random matrix not correctly apended on after first iteration:"
, , 1

           [,1]      [,2]
[1,] -1.2070657  1.084441
[2,]  0.2774292 -2.345698

, , 2

     [,1] [,2]
[1,]    0    0
[2,]    0    0

, , 3

     [,1] [,2]
[1,]    0    0
[2,]    0    0

[1] "New random matrix that should be appended is:"
          [,1]       [,2]
[1,] 0.4291247 -0.5747400
[2,] 0.5060559 -0.5466319
[1] "New random matrix not correctly apended on after first iteration:"
, , 1

           [,1]      [,2]
[1,] -1.2070657  1.084441
[2,]  0.2774292 -2.345698

, , 2

          [,1]       [,2]
[1,] 0.4291247 -0.5747400
[2,] 0.5060559 -0.5466319

, , 3

     [,1] [,2]
[1,]    0    0
[2,]    0    0

[1] "New random matrix that should be appended is:"
           [,1]       [,2]
[1,] -0.5644520 -0.4771927
[2,] -0.8900378 -0.9983864
[1] "New random matrix not correctly apended o